apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-access-api
spec:
  template:
    spec:
      serviceAccountName: store-access-api
      containers:
        - name: store-access-api
          envFrom:
            - secretRef:
                name: doro-erp-store-access-runtime
          volumeMounts:
            - name: runtime-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: runtime-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: store-access-api
