apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-access-api
  labels:
    app.kubernetes.io/name: store-access-api
    app.kubernetes.io/part-of: doro-erp
  annotations:
    alb.ingress.kubernetes.io/group.order: "20"
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  ingressClassName: doro-cell-alb
  rules:
    - http:
        paths:
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: store-access-api
                port:
                  name: http
          - path: /api/v1/kiosk-auth
            pathType: Prefix
            backend:
              service:
                name: store-access-api
                port:
                  name: http
          - path: /api/v1/kiosk-devices
            pathType: Prefix
            backend:
              service:
                name: store-access-api
                port:
                  name: http
          - path: /api/v1/security-history
            pathType: Prefix
            backend:
              service:
                name: store-access-api
                port:
                  name: http
          - path: /api/v1/store
            pathType: Prefix
            backend:
              service:
                name: store-access-api
                port:
                  name: http
          - path: /api/v1/employees
            pathType: Prefix
            backend:
              service:
                name: store-access-api
                port:
                  name: http
          - path: /api/v1/tables
            pathType: Prefix
            backend:
              service:
                name: store-access-api
                port:
                  name: http
