apiVersion: v1
kind: Service
metadata:
  name: queue-api
  labels:
    app.kubernetes.io/name: queue-api
    app.kubernetes.io/part-of: doro-erp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: queue-api
  ports:
    - name: http
      port: 8084
      targetPort: http
      protocol: TCP
      appProtocol: http
