apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: store-access-migration
spec:
  provider: aws
  secretObjects:
    - secretName: doro-erp-store-access-migration
      type: Opaque
      data:
        - { objectName: DB_MIGRATION_USERNAME, key: DB_MIGRATION_USERNAME }
        - { objectName: DB_MIGRATION_PASSWORD, key: DB_MIGRATION_PASSWORD }
  parameters:
    region: ap-northeast-2
    usePodIdentity: "true"
    objects: |
      - objectName: "doro-erp/dev/alpha/migration/store-access"
        objectType: "secretsmanager"
        jmesPath:
          - { path: "DB_MIGRATION_USERNAME", objectAlias: "DB_MIGRATION_USERNAME" }
          - { path: "DB_MIGRATION_PASSWORD", objectAlias: "DB_MIGRATION_PASSWORD" }
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: commerce-migration
spec:
  provider: aws
  secretObjects:
    - secretName: doro-erp-commerce-migration
      type: Opaque
      data:
        - { objectName: DB_MIGRATION_USERNAME, key: DB_MIGRATION_USERNAME }
        - { objectName: DB_MIGRATION_PASSWORD, key: DB_MIGRATION_PASSWORD }
  parameters:
    region: ap-northeast-2
    usePodIdentity: "true"
    objects: |
      - objectName: "doro-erp/dev/alpha/migration/commerce"
        objectType: "secretsmanager"
        jmesPath:
          - { path: "DB_MIGRATION_USERNAME", objectAlias: "DB_MIGRATION_USERNAME" }
          - { path: "DB_MIGRATION_PASSWORD", objectAlias: "DB_MIGRATION_PASSWORD" }
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: payment-migration
spec:
  provider: aws
  secretObjects:
    - secretName: doro-erp-payment-migration
      type: Opaque
      data:
        - { objectName: DB_MIGRATION_USERNAME, key: DB_MIGRATION_USERNAME }
        - { objectName: DB_MIGRATION_PASSWORD, key: DB_MIGRATION_PASSWORD }
  parameters:
    region: ap-northeast-2
    usePodIdentity: "true"
    objects: |
      - objectName: "doro-erp/dev/alpha/migration/payment"
        objectType: "secretsmanager"
        jmesPath:
          - { path: "DB_MIGRATION_USERNAME", objectAlias: "DB_MIGRATION_USERNAME" }
          - { path: "DB_MIGRATION_PASSWORD", objectAlias: "DB_MIGRATION_PASSWORD" }
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: queue-migration
spec:
  provider: aws
  secretObjects:
    - secretName: doro-erp-queue-migration
      type: Opaque
      data:
        - { objectName: DB_MIGRATION_USERNAME, key: DB_MIGRATION_USERNAME }
        - { objectName: DB_MIGRATION_PASSWORD, key: DB_MIGRATION_PASSWORD }
  parameters:
    region: ap-northeast-2
    usePodIdentity: "true"
    objects: |
      - objectName: "doro-erp/dev/alpha/migration/queue"
        objectType: "secretsmanager"
        jmesPath:
          - { path: "DB_MIGRATION_USERNAME", objectAlias: "DB_MIGRATION_USERNAME" }
          - { path: "DB_MIGRATION_PASSWORD", objectAlias: "DB_MIGRATION_PASSWORD" }
