apiVersion: v1
kind: ServiceAccount
metadata:
  name: store-access-migration
  labels:
    app.kubernetes.io/name: store-access-migration
    app.kubernetes.io/part-of: doro-erp
    app.kubernetes.io/component: database-migration
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commerce-migration
  labels:
    app.kubernetes.io/name: commerce-migration
    app.kubernetes.io/part-of: doro-erp
    app.kubernetes.io/component: database-migration
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-migration
  labels:
    app.kubernetes.io/name: payment-migration
    app.kubernetes.io/part-of: doro-erp
    app.kubernetes.io/component: database-migration
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: queue-migration
  labels:
    app.kubernetes.io/name: queue-migration
    app.kubernetes.io/part-of: doro-erp
    app.kubernetes.io/component: database-migration
